### ISSUE TITLE
Name check widget

### ISSUE THREAD

**Issue by wengleong** [SproutAsia/sprout-website-js#2]
As a potential lead for incorporation, I may be interested in free tools that allow me to check if my desired company name is available via a free tool on the website.

This will be embedded into our website as a new page

Examples:
- https://www.singaporecompanyincorporation.sg/tool/singapore-business-name-checker/
- https://osome.com/sg/incorporation/for-locals/?utm_source=google&utm_medium=cpc&utm_campaign=incorporation_company_sg_search&utm_content=SRC:g%7CSRCT:%7CCAMP:1618635507%7CGR:116871915992%7CB:491522779599%7CKW:%7CKWID:dsa-1129033622571%7CP:%7CDT:c%7CREG:9062546%7Crin%7C&utm_term=&gclid=EAIaIQobChMIi5_V3PWM8wIVK5lmAh10NQR7EAAYASAAEgLqofD_BwE

Database source: data.gov.sg to avoid API charges. 

Additional logic required to screen if name are available -> not only exact match https://www.acra.gov.sg/how-to-guides/before-you-start/reserving-a-business-name ![Screenshot 2021-09-20 at 2.29.38 PM.png](https://images.zenhubusercontent.com/6118be70e87c3b14c6d566a8/9363048d-5a27-45a1-85d2-0872ad24b036)

**Comment by cbsprout** [comment]
Dev Review - On Going 
For Review on Monday by Daphne
