### ISSUE TITLE
SSIC business activity search

### ISSUE THREAD

**Issue by wengleong** [SproutAsia/sprout-website-js#3]

**Comment by wengleong** [comment]
As a potential lead, I want to be able to search for business activities that I can register for the company on free tools before I decide to proceed with an incorporation.

This will be embedded into our website as a new page

Examples:
- https://osome.com/sg/ssic-code-search-tool/
- https://www.rikvin.com/tools/ssic-codes/

Database
- [https://app.zenhub.com/files/374527368/c9004f15-37fd-4d85-bc4c-89aa9aad5642/download](https://app.zenhub.com/files/374527368/c9004f15-37fd-4d85-bc4c-89aa9aad5642/download)

**Comment by bramsproutasia** [comment]
hi @wengleong, currently i store SSIC data in js file and make fast to access it, do you want to change this to save into a database like mysql, mongodb?

**Comment by wengleong** [comment]
I think there is no need for SSIC because it will be relatively static and the db is quite small (change only every few years), we may want to discuss for the company name check. Company we want to extract into AT for analysis too
